### ISSUE TITLE
peerDependency warning with TypeScript 4

### ISSUE THREAD

**Issue by maranomynet** [gund/eslint-plugin-deprecation#11]
I'm using TypeScript 4 in a few projects and it triggers a warning that this plugin specifies TypeScript ^3.7 as a peerDependency.

Should the peerDependency be changed to include TS4?

**Comment by gund** [comment]
Hey @maranomynet, sure we can add typescript@^4 to the version range.

Just to clarify, does this plugin still work with TS v4?

Also if you want you may submit a PR with this change =)

**Comment by maranomynet** [comment]
It does seem to work just fine still.

However, similar to VSCode's built in strike-through warning, it only warns about reading deprecated values, but not about writing/setting them.

Which feels a bit strange omission, IMO

**Comment by gund** [comment]
Thanks for the PR! There is just one little comment.

Regarding deprecated writes it is probably an issue we can open and track.

**Comment by maranomynet** [comment]
I opened issue #13

**Comment by gund** [comment]
Great! The PR is merged and new version will be released soon.

Thanks!
