### ISSUE TITLE
TypeScript 4 peerDependency fix not published to NPM

### ISSUE THREAD

**Issue by hithomasmorelli** [gund/eslint-plugin-deprecation#16]
When installing this plugin on a TypeScript 4 project, I get the error described in #11 (and fixed in #12). However, since this plugin hasn't been published to NPM since #12 was merged, the fix isn't yet doing anything.

Would it be possible for an updated version to be published to NPM?

**Comment by gund** [comment]
Ah true, since the commit message did not follow conventional commits spec it did not trigger autorelease.

Sorry I did not catch that earlier.
I will create a proper commit to publish changes soon.

Thanks.

**Comment by gund** [comment]
Okay so the [new commit](https://github.com/gund/eslint-plugin-deprecation/commit/0e31d0c66bbf9e6b8dd5aafdae39f9df1923a640) is pushed and once it's CI is finished the version should be on NPM =)

**Comment by gund** [comment]
Okay, it's published in https://github.com/gund/eslint-plugin-deprecation/commit/60d837711c5049ac6453a2728f9fc52a193dff11

**Comment by hithomasmorelli** [comment]
@gund Brilliant, thanks!
