### ISSUE TITLE
jsdoc/tsdoc not parsed correctly

### ISSUE THREAD

**Issue by alumni** [gund/eslint-plugin-deprecation#29]
Seems that the deprecation message is shown as `[object Object]`, after upgrading TypeScript 4.3:

![image](https://user-images.githubusercontent.com/611745/125402311-8df20900-e3b4-11eb-9cfa-b7542c581d67.png)

**Comment by Sven65** [comment]
I am also experiencing this issue.

**Comment by bfaulk96** [comment]
I am also seeing this issue.

**Comment by caspardue** [comment]
I think it breaks because of this change in the typescript AST: https://github.com/microsoft/TypeScript/pull/41877

**Comment by jleider** [comment]
While we are waiting for these things to be merged I created a quick and dirty release with #33 and #38. 

Just add the following to your `package.json`:

`"eslint-plugin-deprecation": "https://github.com/jleider/eslint-plugin-deprecation#v1.3.0"`

**Comment by gund** [comment]
The fix is being prepared in #35

**Comment by gund** [comment]
Released in v1.3.1!
