### ISSUE TITLE
Typescript v5 support

### ISSUE THREAD

**Issue by gund** [gund/eslint-plugin-deprecation#60]
This issue tracks a support for Typescript v5.

Before the following steps are done Typescript v5 support will NOT land into latest release:
- [x] Update Typescript to v5 in dev dependencies and make sure tests are passing
- [x] Add backwards compatibility tests for Typescript v4
- [x] Add stable Typescript v5 to peer dependencies
- [x] [Typescript v5 is released](https://github.com/microsoft/TypeScript/issues/51362) as stable

If you already would like to play around with Typescript v5 beta you can try `@next` NPM tag version of this package which includes Typescript v5 beta in it's peer dependencies.

If you find any issues with it you may report them in this issue or open a PR to `next` branch with a fix.
Any fixes merged into `next` branch will be automatically released under `@next` NPM release tag.

**Comment by Profesor08** [comment]
There are some issues with `tsconfig.test.json`, which cause tests to fail, all of them.

**Comment by dscalzi** [comment]
@josundt you can try installing `[1.4.0-next.1](https://github.com/gund/eslint-plugin-deprecation/releases/tag/v1.4.0-next.1)`

**Comment by gund** [comment]
Final release for TS v5 support has been published in [`v1.4.0-next.2`](https://github.com/gund/eslint-plugin-deprecation/releases/tag/v1.4.0-next.2)!

Could you please try it out on your projects and let me know if it's working fine so we can proceed with the latest release?

**Comment by amikheychik** [comment]
@gund I've just tried v1.4.0-next.2 with TS v5.0.3 and getting `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` as on v1.3.0. (https://gist.github.com/amikheychik/2c138a6f7be88c0d2723d52834bde2cd)

**Comment by maxnowack** [comment]
> @gund I've just tried v1.4.0-next.2 with TS v5.0.3 and getting `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` as on v1.3.0. ([gist.github.com/amikheychik/2c138a6f7be88c0d2723d52834bde2cd](https://gist.github.com/amikheychik/2c138a6f7be88c0d2723d52834bde2cd))

Same issue on my side

**Comment by gund** [comment]
Wow that is unexpected as we did not change any code at all since the last release...
Does anyone has more logs maybe on last stack trace to see maybe there is somewhere an infinity loop or something?
I have completely no idea where to look right now 🤷‍♂️

**Comment by gund** [comment]
Btw are you testing new version with the updated typescript-eslint package versions?
At least [v5.55.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.55.0) is needed for TS5 compatibility.

**Comment by maxnowack** [comment]
I'm using `v5.57.0` and typescript @ `v5.0.3`. I digged down a bit and it seems, that the error isn't related to `eslint-plugin-deprecation` as the issue also occurs if I remove this package and the related configuration.
@amikheychik can you confirm this?

**Comment by amikheychik** [comment]
@maxnowack you're right. I just assumed it's `eslint-plugin-deprecation`, because it was the only one with version limitation and not latest.

@gund sorry about false alarm :)

**Comment by amikheychik** [comment]
@maxnowack it looks like in my case, the problem is with `tsconfig.json`: I'm extending a configuration from another package and it was not working. Once I copied the config, the build started working and after that the linters worked fine too.

**Comment by gund** [comment]
Nice, so we have one confirmation that support for v5 works. Let's wait for a few more and then we can publish it on latest.
I think by the end of today we can do it.
Also there is still probably a 24hr cooldown from NPM until we can publish next release as it was published yesterday by mistake in the automation - so anyway we have to wait a bit 😁

**Comment by SchroederSteffen** [comment]
I tried it in a NestJS project together with several other ESLint plugins and it worked fine. 👍

**Comment by mscharley** [comment]
I haven't tried `v1.4.0-next.2` yet, but I was using `v1.4.0-next.1` in a few projects without issue.

**Comment by josundt** [comment]
Same experience as mscharley
