### ISSUE TITLE
Describe usage

### ISSUE THREAD

**Issue by glensc** [gund/eslint-plugin-deprecation#65]
Describe usage, or point to original documentation.

What is considered deprecation? How do you define deprecations? Is some annotation like `@deprecated` used in docblocks?

**Comment by gund** [comment]
There was no documentation, whatever is marked with `@deprecated` is considered deprecated.
You can find docs on docblocks on the internet but this is out of scope of this package to document how deprecations work.
If you want to add specific link you are free to open a PR with a change to readme.md file.

**Comment by gund** [comment]
There are no levels - deprecated means deprecated.
Lint rule will tell if you are using any deprecated code not if some library is using it.
