### ISSUE TITLE
recommended config

### ISSUE THREAD

**Issue by Zamiell** [gund/eslint-plugin-deprecation#68]
Hello, and thanks for the plugin, which I use in my TypeScript projects.

Most ESLint plugins contain a `recommended` config, which simplifies usage of the plugin.

Since this plugin only provides one rule, a `recommended` can simply setup for end users. Such a config would automatically enable the plugin and automatically enable the rule.

In other words, this is currently the config that I have to have in order to use this plugin:

```ts
const config = {
  plugins: [
    "deprecation",
    // Other plugins enabled here.
  ],
  rules: {
    "deprecation/deprecation": "error",
    // Other rules enabled here.
  },
};
```

But this could/should be simplified to:

```ts
const config = {
  extends: [
    "plugin:deprecation/recommended",
  ],
};
```

If you agree that this is a good idea, I will submit a PR, as setting this up is relatively simple.

**Comment by gund** [comment]
Looks like a nice proposal.
Surely a PR is welcome for this feature!
