### ISSUE TITLE
Add option to ignore own deprecations

### ISSUE THREAD

**Issue by ST-DDT** [gund/eslint-plugin-deprecation#82]
It would be nice to have an option to ignore own deprecated code.
(Own code = code imported from within the same project and not via dependency)

I would like to turn off deprecation warnings inside my tests, because deprecated code still needs tests, but I would like to know if other libraries that I use in the tests are getting deprecated.

**Comment by gund** [comment]
We already discussed this topic in [this issue](https://github.com/gund/eslint-plugin-deprecation/issues/2#issuecomment-614180730) that figuring out which code is considered "yours" and which not is a tricky and is in many cases not fixed definition.

This basically means that we are not going to implement any conditional logic around code ownership etc., to keep this plugin as simple as possible.
If you need to ignore some files in your project - you can configure your eslint rules to apply to the files however you like.

I will be closing this as it's out of scope for this rule.
