### ISSUE TITLE
ESLint Flat Config compatibility

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [gund/eslint-plugin-deprecation#85]
Separately from #78: ESLint 8 already supports flat config, in advance of ESLint 9. Would a small PR that adds in flat config before the full #79 lands be of interest?

**Comment by gund** [comment]
Hey @JoshuaKGoldberg! Sure a small PR would be great to review and merge.
Does #86 address this issue or is another PR needed here?

**Comment by JoshuaKGoldberg** [comment]
Heya! #86 should fix this issue, yes.
