### ISSUE TITLE
Please migrate this Plugin to be used with the new Flat Config for ESLint v9

### ISSUE THREAD

**Issue by rkhanna1997** [gund/eslint-plugin-deprecation#89]
This Plugin is a very useful tool that I have been using since quite some time. However, since recently we have migrated to ESLint v9 and it would be very helpful if this Plugin can be migrated to use the new Flat Config of the ESLint.

**Comment by ReinisV** [comment]
looks like this plugin has been abandoned, last commit was 5 months ago.
@gund want to add a goodbye message at the top of the readme file and archive the repo?

**Comment by gund** [comment]
Yes, the rule has been migrated to `typescript-elsint` project, you can see [the docs here](https://typescript-eslint.io/rules/no-deprecated).
I will update readme accordingly.
